version: '3.8'

services:
  ros:
    tty: true
    stdin_open: true
    build:
      dockerfile: allegro_hand.dockerfile
    ports:
      - "8087:8087"  # Forward ZMQ port for Oculus
      - "8089:8089"  # Forward ZMQ port for transformation
      - "15001:15001"  # Forward port for 2D visualizer component
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
